# Generated by Django 6.0.1 on 2026-01-16 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Short summary of what was learned')),
                ('key_points', models.JSONField(default=list, help_text='List of key takeaways')),
                ('common_mistakes', models.TextField(blank=True, help_text='Common mistakes to avoid')),
                ('code_snippet', models.TextField(blank=True, help_text='Code example or snippet')),
                ('code_language', models.CharField(blank=True, help_text='Programming language for syntax highlighting', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='capsule_images/')),
                ('is_public', models.BooleanField(default=False, help_text='Allow others to view this capsule')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='playlists.playlistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'playlist_item')},
            },
        ),
        migrations.CreateModel(
            name='CapsuleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='capsules.knowledgecapsule')),
            ],
            options={
                'unique_together': {('user', 'capsule')},
            },
        ),
    ]
