# Generated by Django 6.0.1 on 2026-01-16 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstreak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress',
            name='playlist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='playlists.playlistitem'),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='learningstreak',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'playlist_item')},
        ),
    ]
